version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: user-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      retries: 10
    volumes:
      - mysqldata:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    depends_on:
      db:
        condition: service_healthy
    command: -url=jdbc:mysql://db:3306/user_db -user=root -password=root migrate
    volumes:
      - ./fly-migrations:/flyway/sql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false  # disable security for dev
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH}
    ports:
      - "5601:5601"
    networks:
      - elk

volumes:
  mysqldata:

networks:
  elk:
    driver: bridge
