version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: user-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      retries: 10
    volumes:
      - mysqldata:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    depends_on:
      db:
        condition: service_healthy
    command: -url=jdbc:mysql://db:3306/user_db -user=root -password=root migrate
    volumes:
      - ./migrations:/flyway/sql

volumes:
  mysqldata:
