services:
  - type: web
    name: user-db
    env: docker
    dockerfilePath: ./Dockerfile.mysql
    plan: free
    disk:
      name: mysqldata
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: root
      - key: MYSQL_DATABASE
        value: user_db

  - type: worker
    name: flyway
    env: docker
    dockerfilePath: ./Dockerfile.flyway
    plan: free
    startCommand: >
      flyway -url=jdbc:mysql://user-db:3306/user_db -user=root -password=root migrate

  - type: web
    name: elasticsearch
    env: docker
    dockerfilePath: ./Dockerfile.elasticsearch
    plan: free
    envVars:
      - key: discovery.type
        value: single-node
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"
      - key: xpack.security.enabled
        value: "false"

  - type: web
    name: kibana
    env: docker
    dockerfilePath: ./Dockerfile.kibana
    plan: free
    envVars:
      - key: ELASTICSEARCH_HOSTS
        value: http://elasticsearch:9200
