apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums
  namespace: user-management
  labels:
    app: ums
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ums
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ums
    spec:
      containers:
        - name: ums
          image: solomonbekele/user-management-system:2.0 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: ums-config
            - secretRef:
                name: ums-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
